version: '3.9'

services:
  zombie_survival:
    container_name: zombie_survival
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./zombie_survival:/zombie_survival
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env